condense_wildcard_suffixes = true
edition = "2021"
error_on_line_overflow = true
#error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Upper"
imports_granularity = "Module"
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
unstable_features = true
use_try_shorthand = true
